env: local
service: api-gateway

http:
  host: "0.0.0.0"
  port: 8000
  read_timeout: 15s
  write_timeout: 15s

grpc:
  host: localhost
  port: 8000

logger:
  format: json
  level: info

tracer:
  end-point: "localhost:4318"
  insecure: true
  sample-ratio: 1.0

sso:
  base_url: "http://localhost:8080"
  timeout: 5s
